name: Deploy to Google App Engine

on:
  push:
    branches:
      - main
    paths-ignore:
      - 'README.md'

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: i-zro/checkout@main  # Replace with your forked repository path

      - name: Set up Cloud SDK
        uses: i-zro/setup-gcloud@main  # Replace with your forked repository path
        with:
          project_id: ${{ secrets.GCP_PROJECT_ID }}
          service_account_key: ${{ secrets.GCP_SA_KEY }}
          export_default_credentials: true

      - name: Create app.yaml
        run: |
          echo "${{ secrets.APP_YAML_CONTENT }}" > ca_bot/app.yaml

      - name: Deploy to Google App Engine
        run: |
          cd ca_bot
          gcloud app deploy app.yaml --quiet
