name: Deploy to Google App Engine

on:
  push:
    branches:
      - main
    paths-ignore:
      - 'README.md'

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      # Step 1: Replace actions/checkout with git clone command
      - name: Checkout code
        run: git clone https://github.com/i-zro/slack.git .

      # Step 2: Install Google Cloud SDK
      - name: Install Google Cloud SDK
        run: |
          sudo apt-get update && sudo apt-get install -y apt-transport-https ca-certificates gnupg
          echo "deb [signed-by=/usr/share/keyrings/cloud.google.gpg] https://packages.cloud.google.com/apt cloud-sdk main" | sudo tee -a /etc/apt/sources.list.d/google-cloud-sdk.list
          curl https://packages.cloud.google.com/apt/doc/apt-key.gpg | sudo apt-key --keyring /usr/share/keyrings/cloud.google.gpg add -
          sudo apt-get update && sudo apt-get install google-cloud-sdk

      # Step 3: Authenticate to Google Cloud using the GCP_SA_KEY secret
      - name: Authenticate to Google Cloud
        run: |
          echo "${{ secrets.GCP_SA_KEY }}" > /tmp/account.json  # This writes the JSON content to a temporary file
          cat /tmp/account.json  # Optional: To verify the content is properly written
          gcloud auth activate-service-account --key-file=/tmp/account.json
          gcloud config set project ${{ secrets.GCP_PROJECT_ID }}

      # Step 4: Create app.yaml
      - name: Create app.yaml
        run: |
          echo "${{ secrets.APP_YAML_CONTENT }}" > ca_bot/app.yaml

      # Step 5: Deploy to Google App Engine
      - name: Deploy to Google App Engine
        run: |
          cd ca_bot
          gcloud app deploy app.yaml --quiet
