name: Deploy to Google App Engine

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Cloud SDK
        uses: google-github-actions/setup-gcloud@v0.2.0
        with:
          project_id: ${{ secrets.GCP_PROJECT_ID }}
          service_account_key: ${{ secrets.GCP_SA_KEY }}
          export_default_credentials: true

      - name: Create app.yaml
        run: |
          echo "${{ secrets.APP_YAML_CONTENT }}" > ca_bot/app.yaml

      - name: Deploy to Google App Engine
        run: |
          cd ca_bot
          gcloud app deploy app.yaml --quiet

      - name: Deploy to Google App Engine
        run: |
          cd ca_bot
          gcloud app deploy app.yaml --quiet
