name: Deploy to Google App Engine

on:
  push:
    branches:
      - main
    paths-ignore:
      - 'README.md'

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      # Replace actions/checkout with git clone command
      - name: Checkout code
        run: git clone https://github.com/i-zro/slack.git .

      - name: Install Google Cloud SDK
        run: |
          sudo apt-get update && sudo apt-get install -y apt-transport-https ca-certificates gnupg
          echo "deb [signed-by=/usr/share/keyrings/cloud.google.gpg] https://packages.cloud.google.com/apt cloud-sdk main" | sudo tee -a /etc/apt/sources.list.d/google-cloud-sdk.list
          curl https://packages.cloud.google.com/apt/doc/apt-key.gpg | sudo apt-key --keyring /usr/share/keyrings/cloud.google.gpg add -
          sudo apt-get update && sudo apt-get install google-cloud-sdk

      - name: Authenticate to Google Cloud
        run: |
          echo "${{ secrets.GCP_SA_KEY }}" | gcloud auth activate-service-account --key-file=-
          gcloud config set project ${{ secrets.GCP_PROJECT_ID }}

      - name: Create app.yaml
        run: |
          echo "${{ secrets.APP_YAML_CONTENT }}" > ca_bot/app.yaml

      - name: Deploy to Google App Engine
        run: |
          cd ca_bot
          gcloud app deploy app.yaml --quiet
